# Generated by Django 2.1.4 on 2019-05-20 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_1', models.TextField()),
                ('image_1', models.ImageField(default='default.jpg', upload_to='genchem')),
                ('content_2', models.TextField()),
                ('image_2', models.ImageField(default='default.jpg', upload_to='genchem')),
                ('content_3', models.TextField()),
                ('image_3', models.ImageField(default='default.jpg', upload_to='genchem')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
