# Generated by Django 2.1.4 on 2019-05-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_auto_20190519_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
