# Generated by Django 2.1.4 on 2019-04-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
