# Generated by Django 2.1.4 on 2019-04-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='text',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
