# Generated by Django 2.1.4 on 2019-04-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_note_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='notenumber',
            field=models.IntegerField(default=None),
        ),
    ]
