# Generated by Django 2.1.4 on 2019-04-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_note_notenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='notenumber',
            field=models.IntegerField(default=1),
        ),
    ]
