# Generated by Django 2.1.4 on 2019-04-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190411_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clip',
            field=models.TextField(default=''),
        ),
    ]
