# Generated by Django 2.1.4 on 2019-05-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190510_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featureImage',
            field=models.ImageField(default='default.jpg', upload_to='blog'),
        ),
    ]
