# Generated by Django 2.1.4 on 2019-05-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
