# Generated by Django 2.1.4 on 2019-05-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecore', '0002_auto_20190523_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
